__include__: [
  '../dataset/waymo_detection.yml',
  '../runtime.yml',
  './include/dataloader.yml',
  './include/optimizer.yml',
  './include/rtdetrv2_r50vd.yml',
]


output_dir: ./output/rtdetrv2_r18vd_120e_waymo_prob_head
task: tu_estimation

RTDETR: 
  decoder: RTDETRTransformerv2

PResNet:
  depth: 18
  freeze_at: -1
  freeze_norm: False
  pretrained: True


HybridEncoder:
  in_channels: [128, 256, 512]
  hidden_dim: 256
  expansion: 0.5


RTDETRTransformerv2:
  num_layers: 3


RTDETRTransformerv2ProbHead:
  feat_channels: [256, 256, 256]
  feat_strides: [8, 16, 32]
  hidden_dim: 256
  num_levels: 3

  num_queries: 300

  num_denoising: 100
  label_noise_ratio: 0.5
  box_noise_scale: 1.0 # 1.0 0.4

  eval_idx: -1

  # NEW
  num_points: [4, 4, 4] # [3,3,3] [2,2,2]
  cross_attn_method: default # default, discrete
  query_select_method: default # default, agnostic 
  num_layers: 3


epoches: 23

optimizer:
  type: AdamW
  params:
    -
      params: '^(?=.*(?:norm|bn)).*$'
      weight_decay: 0.


train_dataloader: 
  dataset: 
    transforms:
      policy:
        epoch: 20
  collate_fn:
    scales: ~
  total_batch_size: 32

val_dataloader:
  total_batch_size: 32

RTDETRCriterionv2:
  weight_dict: {loss_vfl: 1, loss_bbox: 5, loss_giou: 2, loss_nll: 1}
  losses: ['vfl', 'boxes', 'nll']
  alpha: 0.75
  gamma: 2.0

  matcher:
    type: HungarianMatcher
    weight_dict: {cost_class: 2, cost_bbox: 5, cost_giou: 2}
    alpha: 0.25
    gamma: 2.0