__include__: [
  '../dataset/coco_detection.yml',
  '../runtime.yml',
  './include/dataloader.yml',
  './include/optimizer.yml',
  './include/rtdetrv2_r50vd.yml',
]

task: tu_estimation
model: RTDETR # uses default model for frechet mean generation as frechet means are not known yet 

RTDETR:
  decoder: TUERTDETRTransformerv2

output_dir: ./output/rtdetrv2_r18vd_120e_coco_tue_frechet_generation

train_calibration_split_path: /home/philip/datasets/coco/annotations/instances_train_calibration_split.json

persistence_confidence_threshold: 0.5
persistence_decoder_layers: null

PResNet:
  depth: 18
  freeze_at: -1
  freeze_norm: False
  pretrained: True


HybridEncoder:
  in_channels: [128, 256, 512]
  hidden_dim: 256
  expansion: 0.5


TUERTDETRTransformerv2:
  num_layers: 3

RTDETRTransformerv2:
  num_layers: 3

RTDETRCriterionv2:
  losses: [vfl, boxes]
  weight_dict:
    loss_vfl: 1
    loss_bbox: 5
    loss_giou: 2


epoches: 120 

optimizer:
  type: AdamW
  params:
    - 
      params: '^(?=.*(?:norm|bn)).*$'
      weight_decay: 0.


train_dataloader:
  dataset:
    transforms:
      ops:
        - {type: Resize, size: [640, 640]}
        - {type: SanitizeBoundingBoxes, min_size: 1}
        - {type: ConvertPILImage, dtype: float32, scale: True}
        - {type: ConvertBoxes, fmt: cxcywh, normalize: True}
      policy:
        name: default
  collate_fn:
    scales: null
  total_batch_size: 16
val_dataloader:
  total_batch_size: 16
